dist: xenial
matrix:
  include:
    - python: 3.7
    - python: 3.6
    - python: 3.5
install: make bootstrap
script: make test && coveralls
branches:
  except:
    - /^v[0-9]/
services:
  - mysql
  - redis-server
