[meta]
name = "dqpy"

[author]
name = "Danqing Liu"
email = "unittest@danqing.io"

[redis]
host = "localhost"
port = 6379
db = 0
charset = "utf-8"
decode_responses = true

[cache]
host = "localhost"
port = 6379
db = 0

[sql]
url = "mysql+pymysql://root@127.0.0.1:3306/dqpy?charset=utf8mb4"
flavor = "mysql"

[dbadmin_sql]
url = "mysql+pymysql://root@127.0.0.1:3306/dqpy_dbadmin?charset=utf8mb4"

[mail]
user = "danqing"

[env]
NUMBER1 = "cornell"
